### ISSUE TITLE
Tagbot Iconic Identity 

### ISSUE THREAD

**Issue by podanrj** [emre/tagbot#2]
hy @emre . I see that you are looking for an identity for the project you are developing. here is some iconic logo for your project. I will add more view if you thought this will help your project. thanks.

![robot](https://user-images.githubusercontent.com/33227399/37868948-d453b64e-2fe1-11e8-8171-70f53d6cf060.png)

**Comment by emre** [comment]
This is looking good @podanrj :)  Can you also put the text somewhere in the logo (tagbot)?

However, note that, also a couple of designers also delivered good work. Can't promise this will be selected.
